@echo off
set PATH=%PATH%;C:\Program Files\Git\cmd;C:\Program Files\GitHub CLI\
echo Initializing Git...
git init
echo Configuring Git...
git config user.email "alameen@example.com"
git config user.name "Alameen"
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit - Timesheet App"
echo Creating GitHub Repo...
gh repo create timesheet-app -y --public --source=. --remote=origin --push
echo Done!
